 Network felipeparaujo_default  Creating
 Network felipeparaujo_default  Created
 Container api1  Creating
 Container api2  Creating
 Container db  Creating
 Container lb  Creating
 Container api2  Created
 Container api1  Created
 Container lb  Created
 Container db  Created
Attaching to api1, api2, db, lb
api2  | panic: unable to open database file: no such file or directory
api2  | 
api2  | goroutine 1 [running]:
api2  | github.com/felipeparaujo/rinha-de-backend-24q1/api.(*App).Listen(0xc00018e000)
api2  | 	/opt/rinha/api/server.go:29 +0x4f0
api2  | main.main()
api2  | 	/opt/rinha/api/cmd/main.go:52 +0x265
api1  | panic: unable to open database file: no such file or directory
api1  | 
api1  | goroutine 1 [running]:
api1  | github.com/felipeparaujo/rinha-de-backend-24q1/api.(*App).Listen(0xc000106000)
api1  | 	/opt/rinha/api/server.go:29 +0x4f0
api1  | main.main()
api1  | 	/opt/rinha/api/cmd/main.go:52 +0x265
lb    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
lb    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
lb    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
lb    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
lb    | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
lb    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
lb    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
lb    | /docker-entrypoint.sh: Configuration complete; ready for start up
db    | The files belonging to this database system will be owned by user "postgres".
db    | This user must also own the server process.
db    | 
db    | The database cluster will be initialized with locale "en_US.utf8".
db    | The default database encoding has accordingly been set to "UTF8".
db    | The default text search configuration will be set to "english".
db    | 
db    | Data page checksums are disabled.
db    | 
db    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db    | creating subdirectories ... ok
db    | selecting dynamic shared memory implementation ... posix
db    | selecting default max_connections ... 100
db    | selecting default shared_buffers ... 128MB
db    | selecting default time zone ... Etc/UTC
db    | creating configuration files ... ok
db    | running bootstrap script ... ok
api2 exited with code 2
api1 exited with code 2
db    | performing post-bootstrap initialization ... ok
db    | syncing data to disk ... ok
db    | 
db    | 
db    | Success. You can now start the database server using:
db    | 
db    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db    | 
db    | initdb: warning: enabling "trust" authentication for local connections
db    | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db    | waiting for server to start.... done
db    | server started
db    | CREATE DATABASE
db    | 
db    | 
db    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-tables.sql
db    | ALTER DATABASE
db    | CREATE TABLE
db    | CREATE INDEX
db    | CREATE INDEX
db    | 
db    | 
db    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/01-functions.sql
db    | CREATE FUNCTION
db    | 
db    | 
db    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/99-seed.sql
db    | INSERT 0 5
db    | 
db    | 
db    | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/postgresql.conf
db    | 
db    | waiting for server to shut down.... done
db    | server stopped
db    | 
db    | PostgreSQL init process complete; ready for start up.
db    | 
lb    | 2024/03/10 18:53:35 [error] 20#20: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:38 [error] 20#20: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.2:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:40 [error] 20#20: *4 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:42 [error] 20#20: *5 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:44 [error] 20#20: *6 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:49 [error] 20#20: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:53 [error] 20#20: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.2:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:55 [error] 20#20: *10 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:57 [error] 20#20: *11 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:53:59 [error] 20#20: *12 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:04 [error] 20#20: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:07 [error] 20#20: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.2:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:09 [error] 20#20: *16 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:11 [error] 20#20: *17 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:13 [error] 20#20: *18 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:18 [error] 20#20: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:21 [error] 20#20: *19 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.2:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:23 [error] 20#20: *22 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:25 [error] 20#20: *23 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:27 [error] 20#20: *24 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:32 [error] 20#20: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.3:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:35 [error] 20#20: *25 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.128.2:8080/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:37 [error] 20#20: *28 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:39 [error] 20#20: *29 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
lb    | 2024/03/10 18:54:41 [error] 20#20: *30 no live upstreams while connecting to upstream, client: 192.168.128.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
db exited with code 0
db exited with code 0
lb exited with code 0
